### ISSUE TITLE
Default journal path node

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/Journalysis#19]
Node that returns the default journal path for a given Revit version.
May be a bit tricky with different flavours of Revit.
Perhaps best to return all journal paths found on the machine and let the user decide but that would make it a UI node.

**Comment by JacobSmall** [comment]
Speaking to modern builds - if this is intended to work with the old school stuff (pre 2015) it may require something more involved, but if you're working with a Revit version older than you're not likely using Dynamo either - even with the various flavors, the journals are always stored in the following format: 

> %LOCALAPPDATA%\Autodesk\Revit\<Product name and release>\Journals

So... getting all directory contents in `%LOCALAPPDATA%\Autodesk\Revit\` will return all installed Revit flavors, and appending `\Journals` to that will get you the journal folder for every Revit version installed. 

It's likely that this you could look into pulling the current Revit instance's version with the Application.Version node form the Clockwork package to find the location of the relevant journal files. Test for lockup when accessing the current instance's journal though.

**Comment by andydandy74** [comment]
Let's have this for the Keyboardshortcuts file as well...
