### ISSUE TITLE
WorksharingSession.HostIP node returning mac addresses rather than IP addresses

### ISSUE THREAD

**Issue by franzhein** [andydandy74/Journalysis#32]
**Describe the bug**
WorksharingSession.HostIP node returning mac addresses rather than IP addresses

**Steps to Reproduce**
See attached image

![worksharingsession hostip](https://user-images.githubusercontent.com/38966801/49190894-57644d00-f3c8-11e8-9115-612f9a2cb35c.PNG)

**Expected behavior**
IP address returned rather than mac address

**My setup**
- Operating System: Win 10
- Dynamo version: 1.3.3

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [X] I am running the *latest available version* of Journalysis

**Comments**
Fantastic package, really useful...great work Andy!

**Comment by andydandy74** [comment]
Yes, I should rename that to ```HostAddress``` since it seems to return IP or MAC addresses based on the environment. Same goes for ```WorksharingSession.ServerIP``` btw - I've seen that one output MAC addresses, too.
