### ISSUE TITLE
Journal.ByPath index out of range error

### ISSUE THREAD

**Issue by rizzoblo** [andydandy74/Journalysis#50]
**Describe the bug**
[
  Traceback (most recent call last):
  File "<string>", line 373, in JournalFromPath
IndexError: index out of range: -1
,
  Traceback (most recent call last):
  File "<string>", line 487, in JournalFromPath
IndexError: index out of range: 1

]

**Steps to Reproduce**
Opened sample files 2.x Journal_Crash Investigator and Journals_Healthcheck.dyn and found that the Journal.bypath gives traceback errors: [
  Traceback (most recent call last):
  File "<string>", line 373, in JournalFromPath
IndexError: index out of range: -1
,
  Traceback (most recent call last):
  File "<string>", line 487, in JournalFromPath
IndexError: index out of range: 1

]

**Expected behavior**
This error feeds nulls into downstream nodes

**My setup**
- Operating System: Windows 10, Revit 22.1.1.516
- Dynamo version: Dynamo Revit 2.12.0.5740

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *latest available version* of Journalysis (2.3.1)

**Comment by andydandy74** [comment]
Hi @rizzoblo, did this hppen with multiple journals or just one specific journal?

**Comment by andydandy74** [comment]
@rizzoblo I made a couple of changes (0e07c815173ed506a18ea1ab84586c670fcb66ab) to the Journal.ByPath node that fix some issues I had with a number of journals not being processed correctly. Perhaps this will fix your issue as well. Try downloading the latest version of that node and replace the existing version in your package directory with it:
https://raw.githubusercontent.com/andydandy74/Journalysis/master/nodes/2.x/Journal.ByPath.dyf
I will probably release an updated version on the package manager early next year.

**Comment by rizzoblo** [comment]
It is still giving me traceback errors.

**Comment by andydandy74** [comment]
@rizzoblo I'm afraid I will need to have a look at the journal file that is causing this. Are you able to share it?

**Comment by bll85** [comment]
I'm also getting this error (line 487). Happens on all journals.
Revit 2022.1, Dynamo 2.12

**Comment by andydandy74** [comment]
@bll85 Would you be willing to provide a sample journal file?

**Comment by bll85** [comment]
[journal.0605.txt](https://github.com/andydandy74/Journalysis/files/8153989/journal.0605.txt)

**Comment by bll85** [comment]
I updated the dyf file from the repository. Error is gone. Thanks

**Comment by andydandy74** [comment]
@bll85 Good to know. I should probably update the package then.

**Comment by andydandy74** [comment]
I believe this should be fixed with the latest commits
